<?php
	function get_the_gram(
		$count = 10,																// How many results display per request
		$cache_time = '-1 hour',										// Negative time that can be converted via strtotime()
		$access_token = '123456789.12345.12345',    	// String, Access Token generated by instagram 							(1)
		$user_id = 123456789												// Int, Instagram User ID 																	(2)
	) {

		$url = 'https://api.instagram.com/v1/users/'.$user_id.'/media/recent/?access_token='.$access_token.'&count='.$count;
		$cache_directory = './app/cache/'; // path to cache folder, name should end in slash, such as './app/cache/'
		$cache_file = $cache_directory.sha1($url).'.json';


		if (file_exists($cache_file) && filemtime($cache_file) > strtotime($cache_time)) {
			// If a cache file exists, and it is newer than 1 hour, use it
			$jsonData = json_decode(file_get_contents($cache_file));
		} else {
			// If file does not exist, create directory and file, or update file with newer json data
			$jsonData = json_decode( file_get_contents($url) );
			$jsonEncode = json_encode($jsonData);

			if( !file_exists($cache_file) ) {
				$method = 'a';
				mkdir($cache_directory, 0755, true);
			} else {
				$method = 'w';
			}

			$fh = fopen($cache_file,$method);
			fwrite($fh, $jsonEncode."\n");
		}

		return $jsonData;
	}
?>
